<?php

namespace App\Models;

use App\Traits\ContentTrait;
use App\Traits\HasTitleValues;
use App\Traits\ImageOptimizer;
use App\Traits\InteractsWithSiteSearch;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;
use Laravel\Scout\Searchable;
use Spatie\Tags\HasTags;

class News extends Model
{
    use HasTags, ContentTrait, Searchable, ImageOptimizer, HasTitleValues, InteractsWithSiteSearch;

    protected $guarded = ['id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::created(function ($item){
//            $item->optimize_image();
//        });
    }

    public function toSearchableArray(): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'sub_title' => $this->sub_title,
            'short_description' => $this->searchPlainText($this->short_description, 1000),
            'body' => $this->searchPlainText($this->body),
            'tags' => $this->searchTags(),
            'author' => $this->searchAuthorName(),
            'author_id' => $this->author_id,
            'categories' => $this->searchCategories(),
            'category_ids' => $this->searchCategoryIds(),
            'publish_at' => $this->searchPublishAt(),
            'created_at' => optional($this->created_at)->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Determine if the model should be searchable.
     * Only index published items.
     */
    public function shouldBeSearchable(): bool
    {
        return $this->status === 'published' && (bool) $this->is_published;
    }

    public function featuredNews()
    {
        return $this->hasMany(FeaturedNews::class);
    }


    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_news');
    }

    public function data()
    {
//        return $this->hasMany(PostData)
    }

//    public function tags()
//    {
//        return $this->belongsToMany(Tag::class, 'news_tag', 'news_id', 'tag_id');
//    }


}
