<?php

namespace App\Models;

use App\Http\Resources\ContentMetaDataResource;
use App\Observers\NewsObserver;
use App\Traits\ContentTrait;
use App\Traits\HasTitleValues;
use App\Traits\ImageOptimizer;
use App\Traits\InteractsWithSiteSearch;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;
use Spatie\Tags\HasTags;

#[ObservedBy([NewsObserver::class])]
class News extends Model
{
    use HasTags, ContentTrait, Searchable, ImageOptimizer, HasTitleValues, InteractsWithSiteSearch, SoftDeletes;

    /**
     * گردش کار تحریریه — Shield permission that gates publishing.
     *
     * Convention: Shield resource permissions are "{prefix}_{resource}"
     * (view_news, create_news, ...). We add the custom prefix "publish" via
     * NewsResource::getPermissionPrefixes(), producing "publish_news".
     * Users holding it (خبرنگار ↛ / دبیر، سردبیر، مدیرمسئول ✓) may publish,
     * schedule, suspend, approve and reject; everyone else can only save
     * drafts or submit for review (در انتظار تأیید).
     */
    public const PUBLISH_PERMISSION = 'publish_news';

    public const STATUS_PENDING_REVIEW = 'pending_review';

    protected $guarded = ['id'];

    protected $casts = [
        'subtitles' => 'array',
        'show_visits' => 'boolean',
        'show_comments' => 'boolean',
        'auto_send_telegram' => 'boolean',
        'auto_send_whatsapp' => 'boolean',
        'telegram_sent_at' => 'datetime',
        'whatsapp_sent_at' => 'datetime',
        'archive_at' => 'datetime',
    ];

    /**
     * Transient (not persisted) reject reason, set by the "بازگشت برای اصلاح"
     * action right before saving so NewsObserver can log and notify with it.
     */
    public ?string $workflowRejectReason = null;

    /**
     * آرشیو خودکار — transient flag set by the cron (app:cron) right before
     * suspending an expired item, so NewsObserver logs the revision with the
     * dedicated "auto_archived" action instead of a generic status change.
     */
    public bool $isAutoArchiving = false;

    /**
     * Can the given (or current) user publish/approve news?
     */
    public static function userCanPublish($user = null): bool
    {
        $user = $user ?? auth()->user();

        try {
            return (bool) $user?->can(self::PUBLISH_PERMISSION);
        } catch (\Throwable) {
            return false;
        }
    }

    /**
     * Users allowed to approve pending news (holders of publish_news —
     * directly or via role — plus super admins). Used for workflow
     * notifications; never throws.
     *
     * @return \Illuminate\Support\Collection<int, \App\Models\User>
     */
    public static function approvers(): \Illuminate\Support\Collection
    {
        $users = collect();

        try {
            $users = $users->merge(User::permission(self::PUBLISH_PERMISSION)->get());
        } catch (\Throwable) {
            // Permission not created yet — fall through to super admins only.
        }

        try {
            $users = $users->merge(User::role('super_admin')->get());
        } catch (\Throwable) {
            // Role missing — ignore.
        }

        return $users->unique('id')->values();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::created(function ($item){
//            $item->optimize_image();
//        });
    }

    public function toSearchableArray(): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'sub_title' => $this->sub_title,
            'short_description' => $this->searchPlainText($this->short_description, 1000),
            'body' => $this->searchPlainText($this->body),
            'tags' => $this->searchTags(),
            'author' => $this->searchAuthorName(),
            'author_id' => $this->author_id,
            'categories' => $this->searchCategories(),
            'category_ids' => $this->searchCategoryIds(),
            'publish_at' => $this->searchPublishAt(),
            'created_at' => optional($this->created_at)->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Determine if the model should be searchable.
     * Only index published items.
     */
    public function shouldBeSearchable(): bool
    {
        return $this->status === 'published' && (bool) $this->is_published;
    }

    public function featuredNews()
    {
        return $this->hasMany(FeaturedNews::class);
    }


    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_news');
    }

    public function revisions()
    {
        return $this->hasMany(NewsRevision::class)->latest('created_at')->latest('id');
    }

    /**
     * Resolve the public URL of an uploaded file, checking the same disks
     * used by ContentTrait::getImageUrl(). Null-safe.
     */
    public function getFileUrl(?string $path): ?string
    {
        if (empty($path)) {
            return null;
        }

        if (Storage::disk('public')->exists($path)) {
            return Storage::disk('public')->url($path);
        }

        if (Storage::disk('media')->exists($path)) {
            return Storage::disk('media')->url($path);
        }

        return null;
    }

    /**
     * Public URL of the main audio/video file of the news item. Null-safe.
     */
    public function getMediaFileUrl(): ?string
    {
        return $this->getFileUrl($this->media_file);
    }

    /**
     * اخبار مرتبط هوشمند — smarter related news:
     * items sharing the most tags first (Spatie tags tables), then recent
     * items from the same categories; excluding self, published only,
     * cached for 10 minutes.
     *
     * @return \Illuminate\Support\Collection<int, \App\Models\News>
     */
    public function relatedSmart(int $limit = 5)
    {
        return Cache::remember(
            "related_news_smart_{$this->id}",
            now()->addMinutes(10),
            function () use ($limit) {
                $related = collect();

                $tagIds = $this->tags()->pluck('tags.id')->all();

                if ($tagIds !== []) {
                    $related = static::query()
                        ->where('id', '!=', $this->id)
                        ->where('status', 'published')
                        ->where('is_published', true)
                        ->whereHas('tags', fn ($query) => $query->whereIn('tags.id', $tagIds))
                        ->withCount([
                            'tags as shared_tags_count' => fn ($query) => $query->whereIn('tags.id', $tagIds),
                        ])
                        ->orderByDesc('shared_tags_count')
                        ->orderByDesc('publish_at')
                        ->take($limit)
                        ->get();
                }

                if ($related->count() < $limit) {
                    $categoryIds = $this->categories()->pluck('categories.id')->all();

                    if ($categoryIds !== []) {
                        $related = $related->concat(
                            static::query()
                                ->where('id', '!=', $this->id)
                                ->whereNotIn('id', $related->pluck('id')->all())
                                ->where('status', 'published')
                                ->where('is_published', true)
                                ->whereHas('categories', fn ($query) => $query->whereIn('categories.id', $categoryIds))
                                ->orderByDesc('publish_at')
                                ->take($limit - $related->count())
                                ->get()
                        );
                    }
                }

                return $related->take($limit)->values();
            }
        );
    }

    /**
     * News-only override of ContentTrait::getRelated() so the news single
     * page gets the smart related list, without changing the shared trait
     * behavior for the other content types (note, video, podcast, ...).
     */
    public function getRelated($limit = 5)
    {
        return ContentMetaDataResource::collection($this->relatedSmart((int) $limit));
    }

    public function data()
    {
//        return $this->hasMany(PostData)
    }

//    public function tags()
//    {
//        return $this->belongsToMany(Tag::class, 'news_tag', 'news_id', 'tag_id');
//    }


}
