<?php

namespace App\Models;

use App\Observers\NewsObserver;
use App\Traits\ContentTrait;
use App\Traits\HasTitleValues;
use App\Traits\ImageOptimizer;
use App\Traits\InteractsWithSiteSearch;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Category;
use Illuminate\Support\Facades\Storage;
use Laravel\Scout\Searchable;
use Spatie\Tags\HasTags;

#[ObservedBy([NewsObserver::class])]
class News extends Model
{
    use HasTags, ContentTrait, Searchable, ImageOptimizer, HasTitleValues, InteractsWithSiteSearch, SoftDeletes;

    protected $guarded = ['id'];

    protected $casts = [
        'subtitles' => 'array',
        'show_visits' => 'boolean',
        'show_comments' => 'boolean',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
//
//        self::created(function ($item){
//            $item->optimize_image();
//        });
    }

    public function toSearchableArray(): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'sub_title' => $this->sub_title,
            'short_description' => $this->searchPlainText($this->short_description, 1000),
            'body' => $this->searchPlainText($this->body),
            'tags' => $this->searchTags(),
            'author' => $this->searchAuthorName(),
            'author_id' => $this->author_id,
            'categories' => $this->searchCategories(),
            'category_ids' => $this->searchCategoryIds(),
            'publish_at' => $this->searchPublishAt(),
            'created_at' => optional($this->created_at)->format('Y-m-d H:i:s'),
        ];
    }

    /**
     * Determine if the model should be searchable.
     * Only index published items.
     */
    public function shouldBeSearchable(): bool
    {
        return $this->status === 'published' && (bool) $this->is_published;
    }

    public function featuredNews()
    {
        return $this->hasMany(FeaturedNews::class);
    }


    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_news');
    }

    public function revisions()
    {
        return $this->hasMany(NewsRevision::class)->latest('created_at')->latest('id');
    }

    /**
     * Resolve the public URL of an uploaded file, checking the same disks
     * used by ContentTrait::getImageUrl(). Null-safe.
     */
    public function getFileUrl(?string $path): ?string
    {
        if (empty($path)) {
            return null;
        }

        if (Storage::disk('public')->exists($path)) {
            return Storage::disk('public')->url($path);
        }

        if (Storage::disk('media')->exists($path)) {
            return Storage::disk('media')->url($path);
        }

        return null;
    }

    /**
     * Public URL of the main audio/video file of the news item. Null-safe.
     */
    public function getMediaFileUrl(): ?string
    {
        return $this->getFileUrl($this->media_file);
    }

    public function data()
    {
//        return $this->hasMany(PostData)
    }

//    public function tags()
//    {
//        return $this->belongsToMany(Tag::class, 'news_tag', 'news_id', 'tag_id');
//    }


}
